import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Booking from "../components/Booking";
import ContactUs from "../components/ContactUs";
import Discount from "../components/Discount";
import Footer from "../components/Footer";
import Navbar from "../components/Navbar";
import Reviews from "../components/Reviews";

export default function Home() {
  return (
      <div className="w-full mx-auto ">
        <Head>
          <title>UK House</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className=" pb-32 bg-black">
          <Navbar />
          <Banner />
          <Booking />
        </header>

        <main className=" bg-black">
          <Discount />
          <Reviews />
          <ContactUs />
        </main>
        <hr />
        <footer className=" bg-black pt-10 pb-10">
          <Footer />
        </footer>
      </div>
  );
}
