import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer';
import Front from '../components/Front'
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Navbar/>
        <Front/>
        <Footer/>
      </main>

      <footer >

      </footer>
    </div>
  )
}
